scope: ResourceGroup
testScenarios:
  - description: Microsoft.AppConfiguration/configurationStores ConfigurationStores_Create
    steps:
      - step: ConfigurationStores_Create
        exampleFile: ../examples/ConfigurationStoresCreate.json
      - step: ConfigurationStores_Delete
        exampleFile: ../examples/ConfigurationStoresDelete.json
