scope: ResourceGroup
testScenarios:
  - description: Microsoft.Security/settings Update a setting for subscription
    steps:
      - step: Update a setting for subscription
        exampleFile: ../examples/Settings/UpdateSetting_example.json
