scope: ResourceGroup
testScenarios:
  - description: >-
      Microsoft.Security/autoProvisioningSettings Create auto provisioning
      settings for subscription
    steps:
      - step: Create auto provisioning settings for subscription
        exampleFile: >-
          ../examples/AutoProvisioningSettings/CreateAutoProvisioningSettingsSubscription_example.json
